### ISSUE TITLE
Issue when running 'pip3 install -r requirements.txt'

### ISSUE THREAD

**Issue by ghost** [jenwilson521/benchmark_PathFX#1]
Recieved the following Error when trying to run `pip3 install -r requirements.txt` for the first time based on the README instructions. 

==================================================================

(pathfxenv) aryahaghighi@Aryas-MacBook-Pro benchmark_PathFX % pip3 install -r requirements.txt        
Collecting appnope==0.1.0
  Using cached appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Collecting bleach==2.1.3
  Using cached bleach-2.1.3-py2.py3-none-any.whl (28 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting decorator==4.2.1
  Using cached decorator-4.2.1-py2.py3-none-any.whl (9.3 kB)
Collecting entrypoints==0.2.3
  Using cached entrypoints-0.2.3-py2.py3-none-any.whl (9.4 kB)
Collecting fastcluster==1.1.24
  Using cached fastcluster-1.1.24-cp36-cp36m-macosx_10_11_x86_64.whl (38 kB)
Collecting html5lib==1.0.1
  Using cached html5lib-1.0.1-py2.py3-none-any.whl (117 kB)
Collecting ipykernel==4.8.2
  Using cached ipykernel-4.8.2-py3-none-any.whl (108 kB)
Collecting ipython==6.2.1
  Using cached ipython-6.2.1-py3-none-any.whl (745 kB)
Collecting ipython-genutils==0.2.0
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting ipywidgets==7.1.2
  Using cached ipywidgets-7.1.2-py2.py3-none-any.whl (68 kB)
Collecting jedi==0.11.1
  Using cached jedi-0.11.1-py2.py3-none-any.whl (250 kB)
Collecting Jinja2==2.10
  Using cached Jinja2-2.10-py2.py3-none-any.whl (126 kB)
Collecting jsonschema==2.6.0
  Using cached jsonschema-2.6.0-py2.py3-none-any.whl (39 kB)
Collecting jupyter==1.0.0
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting jupyter-client==5.2.3
  Using cached jupyter_client-5.2.3-py2.py3-none-any.whl (89 kB)
Collecting jupyter-console==5.2.0
  Using cached jupyter_console-5.2.0-py2.py3-none-any.whl (20 kB)
Collecting jupyter-core==4.4.0
  Using cached jupyter_core-4.4.0-py2.py3-none-any.whl (126 kB)
Collecting setuptools==45
  Using cached setuptools-45.0.0-py2.py3-none-any.whl (583 kB)
Collecting MarkupSafe==1.0
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/aryahaghighi/opt/anaconda3/envs/pathfxenv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x_/gtptclls0hz73b9t2l1t8wfm0000gn/T/pip-install-qgofvfpy/markupsafe_3eb9da6e544f4b40b4c4cf405740e743/setup.py'"'"'; __file__='"'"'/private/var/folders/x_/gtptclls0hz73b9t2l1t8wfm0000gn/T/pip-install-qgofvfpy/markupsafe_3eb9da6e544f4b40b4c4cf405740e743/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/x_/gtptclls0hz73b9t2l1t8wfm0000gn/T/pip-pip-egg-info-ly1ydp50
         cwd: /private/var/folders/x_/gtptclls0hz73b9t2l1t8wfm0000gn/T/pip-install-qgofvfpy/markupsafe_3eb9da6e544f4b40b4c4cf405740e743/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x_/gtptclls0hz73b9t2l1t8wfm0000gn/T/pip-install-qgofvfpy/markupsafe_3eb9da6e544f4b40b4c4cf405740e743/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#sha256=a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665 (from https://pypi.org/simple/markupsafe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement MarkupSafe==1.0 (from versions: 0.9, 0.9.1, 0.9.2, 0.9.3, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0, 1.1.0, 1.1.1, 2.0.0a1, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1)
ERROR: No matching distribution found for MarkupSafe==1.0

**Comment by ghost** [comment]
I was able to resolve this technical issue from this post: https://github.com/Netflix/flamescope/issues/120

Run `pip3 install setuptools==45` 

Running `pip3 install -r requirements.txt` outputs the following which I believe fixes the issue. The README should note this. 

==================================================================

pathfxenv) aryahaghighi@Aryas-MacBook-Pro benchmark_PathFX % pip3 install setuptools==45
Collecting setuptools==45
  Using cached setuptools-45.0.0-py2.py3-none-any.whl (583 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 52.0.0.post20210125
    Uninstalling setuptools-52.0.0.post20210125:
      Successfully uninstalled setuptools-52.0.0.post20210125
Successfully installed setuptools-45.0.0
(pathfxenv) aryahaghighi@Aryas-MacBook-Pro benchmark_PathFX % pip3 install setuptools==45     
Requirement already satisfied: setuptools==45 in /Users/aryahaghighi/opt/anaconda3/envs/pathfxenv/lib/python3.6/site-packages (45.0.0)
(pathfxenv) aryahaghighi@Aryas-MacBook-Pro benchmark_PathFX % pip3 install -r requirements.txt
Collecting appnope==0.1.0
  Using cached appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Collecting bleach==2.1.3
  Using cached bleach-2.1.3-py2.py3-none-any.whl (28 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting decorator==4.2.1
  Using cached decorator-4.2.1-py2.py3-none-any.whl (9.3 kB)
Collecting entrypoints==0.2.3
  Using cached entrypoints-0.2.3-py2.py3-none-any.whl (9.4 kB)
Collecting fastcluster==1.1.24
  Using cached fastcluster-1.1.24-cp36-cp36m-macosx_10_11_x86_64.whl (38 kB)
Collecting html5lib==1.0.1
  Using cached html5lib-1.0.1-py2.py3-none-any.whl (117 kB)
Collecting ipykernel==4.8.2
  Using cached ipykernel-4.8.2-py3-none-any.whl (108 kB)
Collecting ipython==6.2.1
  Using cached ipython-6.2.1-py3-none-any.whl (745 kB)
Collecting ipython-genutils==0.2.0
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting ipywidgets==7.1.2
  Using cached ipywidgets-7.1.2-py2.py3-none-any.whl (68 kB)
Collecting jedi==0.11.1
  Using cached jedi-0.11.1-py2.py3-none-any.whl (250 kB)
Collecting Jinja2==2.10
  Using cached Jinja2-2.10-py2.py3-none-any.whl (126 kB)
Collecting jsonschema==2.6.0
  Using cached jsonschema-2.6.0-py2.py3-none-any.whl (39 kB)
Collecting jupyter==1.0.0
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting jupyter-client==5.2.3
  Using cached jupyter_client-5.2.3-py2.py3-none-any.whl (89 kB)
Collecting jupyter-console==5.2.0
  Using cached jupyter_console-5.2.0-py2.py3-none-any.whl (20 kB)
Collecting jupyter-core==4.4.0
  Using cached jupyter_core-4.4.0-py2.py3-none-any.whl (126 kB)
Requirement already satisfied: setuptools==45 in /Users/aryahaghighi/opt/anaconda3/envs/pathfxenv/lib/python3.6/site-packages (from -r requirements.txt (line 19)) (45.0.0)
Collecting MarkupSafe==1.0
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
Collecting matplotlib==2.0.2
  Downloading matplotlib-2.0.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 1.9 MB/s 
Collecting mistune==0.8.3
  Downloading mistune-0.8.3-py2.py3-none-any.whl (16 kB)
Collecting nbconvert==5.3.1
  Downloading nbconvert-5.3.1-py2.py3-none-any.whl (387 kB)
     |████████████████████████████████| 387 kB 48.5 MB/s 
Collecting nbformat==4.4.0
  Downloading nbformat-4.4.0-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 23.1 MB/s 
Collecting networkx==1.11
  Downloading networkx-1.11-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 27.8 MB/s 
Collecting notebook==5.4.0
  Downloading notebook-5.4.0-py2.py3-none-any.whl (8.0 MB)
     |████████████████████████████████| 8.0 MB 62.4 MB/s 
Collecting numpy==1.13.3
  Downloading numpy-1.13.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 47.5 MB/s 
Collecting pandas==0.20.3
  Downloading pandas-0.20.3-cp36-cp36m-macosx_10_12_x86_64.whl (9.3 MB)
     |████████████████████████████████| 9.3 MB 50.4 MB/s 
Collecting pandocfilters==1.4.2
  Using cached pandocfilters-1.4.2.tar.gz (14 kB)
Collecting parso==0.1.1
  Downloading parso-0.1.1-py2.py3-none-any.whl (91 kB)
     |████████████████████████████████| 91 kB 27.8 MB/s 
Collecting pexpect==4.4.0
  Downloading pexpect-4.4.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 13.1 MB/s 
Collecting pickleshare==0.7.4
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl (6.9 kB)
Collecting prompt-toolkit==1.0.15
  Downloading prompt_toolkit-1.0.15-py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 30.3 MB/s 
Collecting ptyprocess==0.5.2
  Downloading ptyprocess-0.5.2-py2.py3-none-any.whl (39 kB)
Collecting Pygments==2.2.0
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841 kB)
     |████████████████████████████████| 841 kB 21.3 MB/s 
Collecting pyparsing==2.2.0
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 8.1 MB/s 
Collecting python-dateutil==2.6.1
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194 kB)
     |████████████████████████████████| 194 kB 66.2 MB/s 
Collecting pytz==2017.2
  Downloading pytz-2017.2-py2.py3-none-any.whl (484 kB)
     |████████████████████████████████| 484 kB 48.7 MB/s 
Collecting pyzmq==17.0.0
  Downloading pyzmq-17.0.0-cp36-cp36m-macosx_10_6_intel.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 38.0 MB/s 
Collecting qtconsole==4.3.1
  Downloading qtconsole-4.3.1-py2.py3-none-any.whl (108 kB)
     |████████████████████████████████| 108 kB 60.2 MB/s 
Collecting scipy==0.19.1
  Downloading scipy-0.19.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.2 MB)
     |████████████████████████████████| 16.2 MB 48.3 MB/s 
Collecting seaborn==0.8.1
  Downloading seaborn-0.8.1.tar.gz (178 kB)
     |████████████████████████████████| 178 kB 36.5 MB/s 
Collecting Send2Trash==1.5.0
  Using cached Send2Trash-1.5.0-py3-none-any.whl (12 kB)
Collecting simplegeneric==0.8.1
  Downloading simplegeneric-0.8.1.zip (12 kB)
Collecting six==1.11.0
  Downloading six-1.11.0-py2.py3-none-any.whl (10 kB)
Collecting terminado==0.8.1
  Downloading terminado-0.8.1-py2.py3-none-any.whl (33 kB)
Collecting testpath==0.3.1
  Downloading testpath-0.3.1-py2.py3-none-any.whl (161 kB)
     |████████████████████████████████| 161 kB 21.8 MB/s 
Collecting tornado==5.0
  Downloading tornado-5.0.tar.gz (504 kB)
     |████████████████████████████████| 504 kB 46.5 MB/s 
Collecting traitlets==4.3.2
  Downloading traitlets-4.3.2-py2.py3-none-any.whl (74 kB)
     |████████████████████████████████| 74 kB 12.4 MB/s 
Collecting wcwidth==0.1.7
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl (21 kB)
Collecting webencodings==0.5.1
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting widgetsnbextension==3.1.4
  Downloading widgetsnbextension-3.1.4-py2.py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 27.5 MB/s 
Collecting openpyxl==3.0.6
  Downloading openpyxl-3.0.6-py2.py3-none-any.whl (242 kB)
     |████████████████████████████████| 242 kB 50.4 MB/s 
Collecting xlrd==2.0.1
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 20.8 MB/s 
Collecting xlwt==1.3.0
  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
     |████████████████████████████████| 99 kB 24.1 MB/s 
Collecting jdcal
  Downloading jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Building wheels for collected packages: MarkupSafe, pandocfilters, seaborn, simplegeneric, tornado
  Building wheel for MarkupSafe (setup.py) ... done
  Created wheel for MarkupSafe: filename=MarkupSafe-1.0-cp36-cp36m-macosx_10_9_x86_64.whl size=15710 sha256=8fb6c7b2867811ac5589247833fb86e58a5eba38c31b508d31d4d5e91bcc9b69
  Stored in directory: /Users/aryahaghighi/Library/Caches/pip/wheels/00/5a/67/e7ff93a250c45c5b91636cc8a0660c888bbb7d2829eaa6ca9d
  Building wheel for pandocfilters (setup.py) ... done
  Created wheel for pandocfilters: filename=pandocfilters-1.4.2-py3-none-any.whl size=7855 sha256=120c74473d647ae3266b579deb356d18a164d5f42fefd20dc62306294bbe6eba
  Stored in directory: /Users/aryahaghighi/Library/Caches/pip/wheels/46/c4/40/718c6fd14c2129ccaee10e0cf03ef6c4d01d98cad5dbbfda38
  Building wheel for seaborn (setup.py) ... done
  Created wheel for seaborn: filename=seaborn-0.8.1-py3-none-any.whl size=184861 sha256=2b0102606deed569c3b33d96dd9774bc009d9e24808b556d24437e9a90c4c037
  Stored in directory: /Users/aryahaghighi/Library/Caches/pip/wheels/b4/8a/f8/954cba570daa622117cc602e6e2cd97b15233d213546348f6e
  Building wheel for simplegeneric (setup.py) ... done
  Created wheel for simplegeneric: filename=simplegeneric-0.8.1-py3-none-any.whl size=5074 sha256=3ba4ce6147662b6f3a299c0595d3e63ade0b5561ace3ef0fbb17799a7f7bb779
  Stored in directory: /Users/aryahaghighi/Library/Caches/pip/wheels/aa/2e/cc/c837f9b4f1927c7bded8233b73a186b2d303daf0af7ecb07f6
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-5.0-cp36-cp36m-macosx_10_9_x86_64.whl size=437869 sha256=623ae16d67817e5a2006d48d9b25c004e27ba0add32da15828287c18fe84f368
  Stored in directory: /Users/aryahaghighi/Library/Caches/pip/wheels/0c/71/36/94ef1715a4e48e218aed41566be76322f50a14316204fbe2ce
Successfully built MarkupSafe pandocfilters seaborn simplegeneric tornado
Installing collected packages: six, ipython-genutils, decorator, webencodings, wcwidth, traitlets, ptyprocess, parso, tornado, simplegeneric, pyzmq, python-dateutil, Pygments, prompt-toolkit, pickleshare, pexpect, MarkupSafe, jupyter-core, jsonschema, jedi, html5lib, appnope, testpath, pandocfilters, nbformat, mistune, jupyter-client, Jinja2, ipython, entrypoints, bleach, terminado, Send2Trash, nbconvert, ipykernel, notebook, widgetsnbextension, pytz, pyparsing, numpy, cycler, scipy, qtconsole, pandas, matplotlib, jupyter-console, jdcal, ipywidgets, et-xmlfile, xlwt, xlrd, seaborn, openpyxl, networkx, jupyter, fastcluster
Successfully installed Jinja2-2.10 MarkupSafe-1.0 Pygments-2.2.0 Send2Trash-1.5.0 appnope-0.1.0 bleach-2.1.3 cycler-0.10.0 decorator-4.2.1 entrypoints-0.2.3 et-xmlfile-1.1.0 fastcluster-1.1.24 html5lib-1.0.1 ipykernel-4.8.2 ipython-6.2.1 ipython-genutils-0.2.0 ipywidgets-7.1.2 jdcal-1.4.1 jedi-0.11.1 jsonschema-2.6.0 jupyter-1.0.0 jupyter-client-5.2.3 jupyter-console-5.2.0 jupyter-core-4.4.0 matplotlib-2.0.2 mistune-0.8.3 nbconvert-5.3.1 nbformat-4.4.0 networkx-1.11 notebook-5.4.0 numpy-1.13.3 openpyxl-3.0.6 pandas-0.20.3 pandocfilters-1.4.2 parso-0.1.1 pexpect-4.4.0 pickleshare-0.7.4 prompt-toolkit-1.0.15 ptyprocess-0.5.2 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 pyzmq-17.0.0 qtconsole-4.3.1 scipy-0.19.1 seaborn-0.8.1 simplegeneric-0.8.1 six-1.11.0 terminado-0.8.1 testpath-0.3.1 tornado-5.0 traitlets-4.3.2 wcwidth-0.1.7 webencodings-0.5.1 widgetsnbextension-3.1.4 xlrd-2.0.1 xlwt-1.3.0
(pathfxenv) aryahaghighi@Aryas-MacBook-Pro benchmark_PathFX %
